### ISSUE TITLE
KeyError: 'framewise_output'

### ISSUE THREAD

**Issue by PasNinii** [qiuqiangkong/audioset_tagging_cnn#13]
Hi,

When I run 
```CUDA_VISIBLE_DEVICES=0 python3 pytorch/inference.py sound_event_detection --model_type=$MODEL_TYPE --checkpoint_path=$CHECKPOINT_PATH --audio_path="resources/7061-6-0-0.wav" --cuda```
I got an error saying 
```
Traceback (most recent call last):
  File "pytorch/inference.py", line 202, in <module>
    sound_event_detection(args)
  File "pytorch/inference.py", line 132, in sound_event_detection
    framewise_output = batch_output_dict['framewise_output'].data.cpu().numpy()[0]
```
Then if I print batch_output_dict I see that the keys are: `dict_keys(['clipwise_output', 'embedding'])`. Am I missing something ?

Thanks

**Comment by jsphweid** [comment]
@PasNinii did you solve this?

**Comment by moseranliunian** [comment]
Hello, I also encountered the same problem when running the code, I would like to ask you how to solve it

**Comment by chamecall** [comment]
that happens because you're using  checkpoints for models that are not supposed to predict framewise predictions.
as said in [here](https://github.com/qiuqiangkong/audioset_tagging_cnn#sound-event-detection-using-pretrained-models) only the DecisionLevelMax (the best), DecisionLevelAvg, DecisionLevelAtt models support such type of predictions. In my turn I'm interested if maybe someone trained such a architecture for more lightweight archs (cnn10, mobilenetv*)?
