### ISSUE TITLE
What's the input size of CNN

### ISSUE THREAD

**Issue by xiaoluobu** [qiuqiangkong/audioset_tagging_cnn#21]
Hello,

I try to print the input size of each layer, take the Cnn14 model code for example:
1. use function librosa.load to load audio wav. [1, 32000]
2. spectrogram_extractor: [1, 1, 1001, 513]
3. logmel_extractor: [1, 1, 1001, 64]

I have three questions:
1. Different audio has different length, for example, some audio may be [1, 32000], others may be [1, 294198], so they have different size after spectrogram_extractor. Why can you input different size of tensor into CNN? Or have you reshape them into the same size?
2. How do you input a (1001, 64) size( not the same width and length) into CNN?
3. I test your model , the accuracy is really high. I try to extract audio features using mfcc, and train the audioset on VGGNet, but the accuracy is about 50%. So how do you improve your model‘s accuracy?

Looking forward to your reply. Thank you.

**Comment by qiuqiangkong** [comment]
Hi! Here are the answers:
1. All audios are padded or truncated to 10 seconds (32000 * 10 samples) before they are input to the CNN. 
2. In training, all input has shapes of (1001, 64). In inference, the input can be arbitrary size (L, 64), because there is a global pooling layer after the CNN. 
3. MFCC should work, but is slightly worse than log mel spectrogram. In PANNs the training is simple, using log mel spectrogram + CNN14 should achieve a good performance. I have not looked into VGGNet yet.

**Comment by xiaoluobu** [comment]
It really helps. Thank you so much for your reply.
